const Router = require('express')
const router = new Router()
const deviceRouter = require('./deviceRouter')
const userRouter = require('./userRouter')
const brandRouter = require('./brandRouter')
const colorRouter = require('./colorRouter')
const typeRouter = require('./typeRouter')
const basketRouter = require('./basketRouter')
const offerRouter = require('./offerRouter')
const EmailSender = require('../email/sender')
const outsideApiController = require('../controllers/outsideApiController')

router.use('/user', userRouter)
router.use('/type', typeRouter)
router.use('/brand', brandRouter)
router.use('/color', colorRouter)
router.use('/device', deviceRouter)
router.use('/basket', basketRouter)
router.use('/offer', offerRouter)
router.post('/email/me', EmailSender.toMe)
router.get('/boxberry/points', outsideApiController.getBoxberryPoints)
router.get('/boxberry/cities', outsideApiController.getBoxberryCities)
router.get('/boxberry/price', outsideApiController.getBoxberryPrice)
router.post('/payment/create', outsideApiController.createPaymentOfferYOOKASSA)
router.post('/payment/check', outsideApiController.checkPaymentOfferYOOKASSA)
router.get('/boxberry/zip', outsideApiController.getBoxberryZip)

module.exports = router